name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  schedule:
    - cron: '30 2 * * *'  # Run once per day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unciv-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Runs a set of commands using the runners shell
      - name: Autoupdate
        continue-on-error: true  # We want to autoupdate even if there are errors
        run: |
          unciv_url=$(curl -s https://api.github.com/repos/yairm210/unciv/releases/latest | grep -o "http.*Unciv.jar")
          wget -q -O Unciv.jar $unciv_url
          java -jar Unciv.jar mod-ci

      - name: Remove Unciv executable
        run: rm Unciv.jar

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Autoupdate

